/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class modern_challenge_Main */

#ifndef _Included_modern_challenge_Main
#define _Included_modern_challenge_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     modern_challenge_Main
 * Method:    sumTwoInt
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_modern_challenge_Main_sumTwoInt
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
