// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$42 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$42() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "lrintl",
        constants$20.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_DOUBLE
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llrint",
        constants$42.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "llrintf",
        constants$42.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "llrintl",
        constants$42.const$1
    );
}


