// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(__setusermatherr$x0.class, "apply", constants$9.const$2);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__setusermatherr",
        constants$9.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sin",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "cos",
        constants$10.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "tan",
        constants$10.const$2
    );
}


