// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("name"),
        JAVA_DOUBLE.withName("arg1"),
        JAVA_DOUBLE.withName("arg2"),
        JAVA_DOUBLE.withName("retval")
    ).withName("_exception");
    static final VarHandle const$1 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$2 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("name"));
    static final VarHandle const$3 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("arg1"));
    static final VarHandle const$4 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("arg2"));
    static final VarHandle const$5 = constants$8.const$0.varHandle(MemoryLayout.PathElement.groupElement("retval"));
}


