// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final VarHandle const$0 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("lc_time_curr"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        JAVA_DOUBLE.withName("x"),
        JAVA_LONG.withName("val"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("low"),
            JAVA_INT.withName("high")
        ).withName("lh")
    ).withName("__mingw_dbl_type_t");
    static final VarHandle const$2 = constants$4.const$1.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$3 = constants$4.const$1.varHandle(MemoryLayout.PathElement.groupElement("val"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("low"),
        JAVA_INT.withName("high")
    ).withName("");
    static final VarHandle const$5 = constants$4.const$4.varHandle(MemoryLayout.PathElement.groupElement("low"));
}


