// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sqrt",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ceil",
        constants$10.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "floor",
        constants$10.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fabsf",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fabsl",
        constants$10.const$2
    );
}


