// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$44 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$44() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llround",
        constants$42.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "llroundf",
        constants$42.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llroundl",
        constants$42.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "trunc",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "truncf",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "truncl",
        constants$10.const$2
    );
}


