// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "atan2l",
        constants$12.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sinhf",
        constants$13.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sinhl",
        constants$10.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "coshf",
        constants$13.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "coshl",
        constants$10.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "tanhf",
        constants$13.const$3
    );
}


