// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$45 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$45() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fmodf",
        constants$26.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fmodl",
        constants$12.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "remainder",
        constants$12.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "remainderf",
        constants$26.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "remainderl",
        constants$12.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_DOUBLE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "remquo",
        constants$45.const$5
    );
}


