// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sinl",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cosf",
        constants$13.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "cosl",
        constants$10.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tanf",
        constants$13.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "tanl",
        constants$10.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "asinf",
        constants$13.const$3
    );
}


