// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "_scalb",
        constants$14.const$1
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_INT,
        JAVA_DOUBLE
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "_finite",
        constants$20.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "_fpclass",
        constants$20.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_isnan",
        constants$20.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "j0",
        constants$10.const$2
    );
}


