// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nextafterl",
        constants$12.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "nexttoward",
        constants$12.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_DOUBLE
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nexttowardf",
        constants$48.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nexttowardl",
        constants$12.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fdim",
        constants$12.const$0
    );
}


