// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fminf",
        constants$26.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fminl",
        constants$12.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_DOUBLE
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fma",
        constants$50.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fmaf",
        constants$50.const$4
    );
}


