// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$29 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$29() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "asinhl",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "atanh",
        constants$10.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "atanhf",
        constants$13.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "atanhl",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "expf",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "expl",
        constants$10.const$2
    );
}


