// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "tanhl",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "acosh",
        constants$10.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "acoshf",
        constants$13.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "acoshl",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "asinh",
        constants$10.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "asinhf",
        constants$13.const$3
    );
}


