// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "_isnanf",
        constants$23.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "_fpclassf",
        constants$23.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "_chgsignl",
        constants$10.const$2
    );
    static final MemorySegment const$3 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("6.0.0");
    static final MemorySegment const$4 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("alpha");
    static final MemorySegment const$5 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("This function or variable may be unsafe, use _CRT_SECURE_NO_WARNINGS to disable deprecation");
}


