// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final VarHandle const$0 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("lc_collate_cp"));
    static final VarHandle const$1 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("lc_clike"));
    static final VarHandle const$2 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("mb_cur_max"));
    static final VarHandle const$3 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("lconv_intl_refcount"));
    static final VarHandle const$4 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("lconv_num_refcount"));
    static final VarHandle const$5 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("lconv_mon_refcount"));
}


