// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fmod",
        constants$12.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        JAVA_DOUBLE,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sincos",
        constants$15.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "sincosl",
        constants$15.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        JAVA_FLOAT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sincosf",
        constants$15.const$4
    );
}


