// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    static final VarHandle const$0 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("f"));
    static final VarHandle const$1 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("ldt"));
    static final VarHandle const$2 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("dt"));
    static final VarHandle const$3 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("ft"));
    static final VarHandle const$4 = RuntimeHelper.POINTER.varHandle();
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("__imp__HUGE", RuntimeHelper.POINTER);
}


