// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__mingw_get_crt_info",
        constants$0.const$0
    );
    static final StructLayout const$2 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("locinfo"),
        RuntimeHelper.POINTER.withName("mbcinfo")
    ).withName("localeinfo_struct");
    static final VarHandle const$3 = constants$0.const$2.varHandle(MemoryLayout.PathElement.groupElement("locinfo"));
    static final VarHandle const$4 = constants$0.const$2.varHandle(MemoryLayout.PathElement.groupElement("mbcinfo"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_SHORT.withName("wLanguage"),
        JAVA_SHORT.withName("wCountry"),
        JAVA_SHORT.withName("wCodePage")
    ).withName("tagLC_ID");
}


