// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "round",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "roundf",
        constants$13.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "roundl",
        constants$10.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "lround",
        constants$20.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "lroundf",
        constants$23.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "lroundl",
        constants$20.const$1
    );
}


