// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fmal",
        constants$50.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "_copysignf",
        constants$26.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "_chgsignf",
        constants$13.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "_logbf",
        constants$13.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_nextafterf",
        constants$26.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "_finitef",
        constants$23.const$2
    );
}


