// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {}
    static final VarHandle const$0 = constants$4.const$4.varHandle(MemoryLayout.PathElement.groupElement("high"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_INT.withName("val")
    ).withName("__mingw_flt_type_t");
    static final VarHandle const$2 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$3 = constants$5.const$1.varHandle(MemoryLayout.PathElement.groupElement("val"));
    static final UnionLayout const$4 = MemoryLayout.unionLayout(
        JAVA_DOUBLE.withName("x"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("low"),
            JAVA_INT.withName("high"),
            MemoryLayout.paddingLayout(8)
        ).withName("lh")
    ).withName("__mingw_ldbl_type_t");
    static final VarHandle const$5 = constants$5.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
}


