// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "cbrt",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "cbrtf",
        constants$13.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "cbrtl",
        constants$10.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "hypot",
        constants$12.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "hypotf",
        constants$26.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "hypotl",
        constants$12.const$0
    );
}


