// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "scalbn",
        constants$14.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "scalbnf",
        constants$32.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "scalbnl",
        constants$14.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "scalbln",
        constants$14.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "scalblnf",
        constants$32.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "scalblnl",
        constants$14.const$1
    );
}


