// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "frexpf",
        constants$31.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "frexpl",
        constants$14.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ilogb",
        constants$20.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "ilogbf",
        constants$23.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ilogbl",
        constants$20.const$1
    );
}


