// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "remquof",
        constants$46.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "remquol",
        constants$45.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "copysign",
        constants$12.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "copysignf",
        constants$26.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "copysignl",
        constants$12.const$0
    );
}


