// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final VarHandle const$0 = constants$0.const$5.varHandle(MemoryLayout.PathElement.groupElement("wLanguage"));
    static final VarHandle const$1 = constants$0.const$5.varHandle(MemoryLayout.PathElement.groupElement("wCountry"));
    static final VarHandle const$2 = constants$0.const$5.varHandle(MemoryLayout.PathElement.groupElement("wCodePage"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("refcount"),
        JAVA_INT.withName("lc_codepage"),
        JAVA_INT.withName("lc_collate_cp"),
        MemoryLayout.sequenceLayout(6, JAVA_INT).withName("lc_handle"),
        MemoryLayout.sequenceLayout(6, MemoryLayout.structLayout(
            JAVA_SHORT.withName("wLanguage"),
            JAVA_SHORT.withName("wCountry"),
            JAVA_SHORT.withName("wCodePage")
        ).withName("tagLC_ID")).withName("lc_id"),
        MemoryLayout.sequenceLayout(6, MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("locale"),
            RuntimeHelper.POINTER.withName("wlocale"),
            RuntimeHelper.POINTER.withName("refcount"),
            RuntimeHelper.POINTER.withName("wrefcount")
        ).withName("")).withName("lc_category"),
        JAVA_INT.withName("lc_clike"),
        JAVA_INT.withName("mb_cur_max"),
        RuntimeHelper.POINTER.withName("lconv_intl_refcount"),
        RuntimeHelper.POINTER.withName("lconv_num_refcount"),
        RuntimeHelper.POINTER.withName("lconv_mon_refcount"),
        RuntimeHelper.POINTER.withName("lconv"),
        RuntimeHelper.POINTER.withName("ctype1_refcount"),
        RuntimeHelper.POINTER.withName("ctype1"),
        RuntimeHelper.POINTER.withName("pctype"),
        RuntimeHelper.POINTER.withName("pclmap"),
        RuntimeHelper.POINTER.withName("pcumap"),
        RuntimeHelper.POINTER.withName("lc_time_curr")
    ).withName("threadlocaleinfostruct");
    static final VarHandle const$4 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("refcount"));
    static final VarHandle const$5 = constants$1.const$3.varHandle(MemoryLayout.PathElement.groupElement("lc_codepage"));
}


