// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "__isnanf",
        constants$23.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "__isnanl",
        constants$20.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "__signbit",
        constants$20.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__signbitf",
        constants$23.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "__signbitl",
        constants$20.const$1
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "sinf",
        constants$13.const$3
    );
}


