// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$47 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$47() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "nan",
        constants$16.const$3
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "nanf",
        constants$47.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "nanl",
        constants$16.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "nextafter",
        constants$12.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "nextafterf",
        constants$26.const$5
    );
}


