// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$38 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$38() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "erfl",
        constants$10.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "erfc",
        constants$10.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "erfcf",
        constants$13.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "erfcl",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "lgamma",
        constants$10.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "lgammaf",
        constants$13.const$3
    );
}


