// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "finite",
        constants$20.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fpclass",
        constants$20.const$1
    );
    static final VarHandle const$2 = JAVA_FLOAT.varHandle();
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("__INFF", JAVA_FLOAT);
    static final VarHandle const$4 = JAVA_DOUBLE.varHandle();
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("__INFL", JAVA_DOUBLE);
}


