// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "lgammal",
        constants$10.const$2
    );
    static final VarHandle const$1 = JAVA_INT.varHandle();
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("signgam", JAVA_INT);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tgamma",
        constants$10.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "tgammaf",
        constants$13.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "tgammal",
        constants$10.const$2
    );
}


