// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct tagLC_ID LC_ID;
 * }
 */
public final class LC_ID extends tagLC_ID {

    // Suppresses default constructor, ensuring non-instantiability.
    private LC_ID() {}
}


