// Generated by jextract

package c.lib.math;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct threadlocaleinfostruct threadlocinfo;
 * }
 */
public final class threadlocinfo extends threadlocaleinfostruct {

    // Suppresses default constructor, ensuring non-instantiability.
    private threadlocinfo() {}
}


